---
title: "R Notebook"
output: html_notebook
---

## Load libraries and functions

```{r}
source("../R/functions.R")
library(data.table)
library(dataplumbr)
library(foreach)
library(doParallel)
library(DBI)
```

```{r}
con <- get_db_conn()
```

#### Function for testing if a string value is a valid date
```{sql connection=con, output.var="qry_res"}
create or replace function is_date(s varchar) 
returns boolean as $$
 begin
   perform s::date;
   return true;
 exception when others then
   return false;
 end;
 $$ language plpgsql;
```

#### Function for cleaning character strings (in this case only removing double quotes). If string is empty after cleaning, returns null.
```{sql connection=con, output.var="qry_res"}
create or replace function clean_char(s varchar) 
returns varchar as $cleaned$
 declare
   cleaned varchar;
 begin
   SELECT NULLIF(REPLACE(s, '"', ''), '') INTO cleaned;
   return cleaned;
 end;
 $cleaned$ language plpgsql;
```

## Create new table of desired columns with correct data types
```{sql connection=con}
CREATE TABLE corelogic_usda.current_tax_200627_typed
(
  geoid_cnty CHAR(5),
  p_id_iris_frmtd VARCHAR(75),
  property_indicator VARCHAR(5),
  zoning VARCHAR(100),
  municipality_name VARCHAR(255),
  municipality_code VARCHAR(20),
  acres NUMERIC(11,2),
  land_square_footage NUMERIC(11,2),
  property_centroid_longitude NUMERIC(9,6),
  property_centroid_latitude NUMERIC(9,6),
  bldg_code VARCHAR(10),
  building_square_feet NUMERIC(9,2),
  living_square_feet NUMERIC(9,2),
  year_built VARCHAR(8),
  effective_year_built VARCHAR(8),
  bedrooms NUMERIC(6,1),
  full_baths NUMERIC(6,1),
  qtr_baths NUMERIC(6,1),
  thrqtr_baths NUMERIC(6,1),
  half_baths NUMERIC(6,1),
  total_baths NUMERIC(6,1),
  situs_address VARCHAR(255),
  situs_zip_code VARCHAR(10),
  mail_address VARCHAR(255),
  mail_zip_code VARCHAR(10),
  sale_code VARCHAR(5),
  sale_price NUMERIC,
  sale_date DATE,
  recording_date DATE,
  transaction_type VARCHAR(5),
  tax_amount NUMERIC,
  tax_year INTEGER,
  assessed_year INTEGER,
  total_value_calculated NUMERIC,
  land_value_calculated NUMERIC,
  improvement_value_calculated NUMERIC
)
```

## Clean and set column data types and insert into new typed table
```{sql connection=con}
  INSERT INTO corelogic_usda.current_tax_200627_typed
  SELECT
  clean_char(fips_code) geoid_cnty, 
  clean_char(p_id_iris_frmtd) p_id_iris_frmtd, 
  clean_char(property_indicator) property_indicator, 
  clean_char(zoning) zoning, 
  clean_char(municipality_name) municipality_name, 
  clean_char(municipality_code) municipality_code,
  CAST(NULLIF(REPLACE(acres, '"', ''), '') AS NUMERIC(11,2)) acres, 
  CAST(NULLIF(REPLACE(land_square_footage, '"', ''), '') AS NUMERIC(11,2)) land_square_footage, 
  CAST(NULLIF(REPLACE(property_centroid_longitude, '"', ''), '') AS NUMERIC(9,6)) property_centroid_longitude, 
  CAST(NULLIF(REPLACE(property_centroid_latitude, '"', ''), '') AS NUMERIC(9,6)) property_centroid_latitude, 
  clean_char(bldg_code) bldg_code, 
  CAST(NULLIF(REPLACE(building_square_feet, '"', ''), '') AS NUMERIC(9,2)) building_square_feet, 
  CAST(NULLIF(REPLACE(living_square_feet, '"', ''), '') AS NUMERIC(9,2)) living_square_feet, 
  clean_char(year_built) year_built, 
  clean_char(effective_year_built) effective_year_built,
  CAST(NULLIF(REPLACE(bedrooms, '"', ''), '') AS NUMERIC(6,1)) bedrooms, 
  CAST(NULLIF(REPLACE(full_baths, '"', ''), '') AS NUMERIC(6,1)) full_baths, 
  CAST(NULLIF(REPLACE("1qtr_baths", '"', ''), '') AS NUMERIC(6,1)) qtr_baths, 
  CAST(NULLIF(REPLACE("3qtr_baths", '"', ''), '') AS NUMERIC(6,1)) thrqtr_baths, 
  CAST(NULLIF(REPLACE(half_baths, '"', ''), '') AS NUMERIC(6,1)) half_baths, 
  CAST(NULLIF(REPLACE(total_baths, '"', ''), '') AS NUMERIC(6,1)) total_baths, 
  trim(
    replace( 
      replace(
        replace(
          coalesce(situs_house_number_prefix, '') || ' ' ||
          coalesce(situs_house_number, '') || ' ' ||
          coalesce(situs_direction, '') || ' ' ||
          coalesce(situs_street_name, '') || ' ' ||
          coalesce(situs_mode, '') || ' ' ||
          coalesce(situs_quadrant, '') || ' ' ||
          coalesce(situs_city, '') || ' ' ||
          coalesce(situs_state, '') || ' ' ||
          coalesce(situs_zip_code, ''),
        '  ', ' '),
      '  ', ' '),
      '"', '')
  ) situs_address, 
  clean_char(situs_zip_code) situs_zip_code, 
  trim(
    replace(
     replace(
       replace(
         coalesce(mail_house_number_prefix, '') || ' ' ||
         coalesce(mail_house_number, '') || ' ' ||
         coalesce(mail_direction, '') || ' ' ||
         coalesce(mail_street_name, '') || ' ' ||
         coalesce(mail_mode, '') || ' ' ||
         coalesce(mail_quadrant, '') || ' ' ||
         coalesce(mail_city, '') || ' ' ||
         coalesce(mail_state, '') || ' ' ||
         coalesce(mail_zip_code, ''),
       '  ', ' '),
     '  ', ' '),
    '"', '')
    ) mail_address, 
  clean_char(mail_zip_code) mail_zip_code,
  clean_char(sale_code) sale_code, 
  CAST(NULLIF(REPLACE(sale_price, '"', ''), '') AS NUMERIC) sale_price, 
  CASE WHEN is_date(REPLACE(sale_date, '"', '')) = TRUE THEN TO_DATE(NULLIF(REPLACE(sale_date, '"', ''), ''), 'YYYYMMDD') ELSE NULL END sale_date,
  CASE WHEN is_date(REPLACE(recording_date, '"', '')) = TRUE THEN TO_DATE(NULLIF(REPLACE(recording_date, '"', ''), ''), 'YYYYMMDD') ELSE NULL END recording_date,
  clean_char(transaction_type) transaction_type,
  CAST(NULLIF(REPLACE(tax_amount, '"', ''), '') AS NUMERIC) tax_amount, 
  CAST(NULLIF(REPLACE(tax_year, '"', ''), '') AS INTEGER) tax_year, 
  CAST(NULLIF(REPLACE(assessed_year, '"', ''), '') AS INTEGER) assessed_year, 
  CAST(NULLIF(REPLACE(total_value_calculated, '"', ''), '') AS NUMERIC) total_value_calculated, 
  CAST(NULLIF(REPLACE(land_value_calculated, '"', ''), '') AS NUMERIC) land_value_calculated,
  CAST(NULLIF(REPLACE(improvement_value_calculated, '"', ''), '') AS NUMERIC) improvement_value_calculated
  FROM corelogic_usda.current_tax_200627_raw;
```

# Add Index
```{sql connection=con}
DROP INDEX IF EXISTS current_tax_200627_typed_geoid_cnty_p_id_iris_frmtd_idx;
CREATE INDEX current_tax_200627_typed_geoid_cnty_p_id_iris_frmtd_idx ON corelogic_usda.current_tax_200627_typed (geoid_cnty, p_id_iris_frmtd);
```

