---
title: "Add Variables by Transorming Existing Columns"
output: 
  html_document:
    toc: yes
    toc_float: yes
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  eval=FALSE
)
```

------------------------------------------------------------------------

## Create sale_year variable

Planned analyses include **analysis by year of sale**. Creating a separate indexed column for year should be faster than repeatedly using DATEPART('year', sale_date).

```{sql}
SELECT DATE_PART('year', sale_date)::INTEGER AS sale_year
```

## Create baths_appraised variable

Using the Fannie Mae and Freddie Mac Uniform Appraisal Dataset Specification to calculate total bathrooms. 3/4 baths count as full baths, 1/4 baths are dropped, half bath is .1 of full bath, so 1 x full bath & 1 x 3/4 bath & 1 x half bath = 2.1 baths (2 full baths, 1 half bath).

We use COALESCE to deal with NULL values because adding NULL values will always return NULL. COALESCE combines values, stopping at the first non-null value. So, if full_baths is NULL, the next non-null value '0' will be used.

We use NULLIF on the result of the baths equation to test if the result is 0. A 0 would indicate that all of the bath types were NULL (it's extremely unlikely to have a house with 0 bathrooms). Therefore, a total value of 0 is converted back to NULL, indicating that we have no information.

```{sql}
NULLIF(COALESCE(full_baths, 0) + 
       COALESCE(thrqtr_baths, 0) + 
       (.1 * COALESCE(half_baths, 0)), 0) AS baths_appraised
```

## Create all new values together, creating a new table

The **fastest** method to add new columns with values to a large dataset is to **write everything to a new table** (as opposed to the very slow operation of running an UPDATE on every record in the existing table). Therefore, we combine the creation of all new columns together in a single query creating a new table.

```{sql}
-- {sql} * Run In psql/pgcli
SELECT *,
       DATE_PART('year', sale_date)::INTEGER AS sale_year,
       NULLIF(coalesce(full_baths, 0) + coalesce(thrqtr_baths, 0) + (.1 * coalesce(half_baths, 0)), 0) AS baths_appraised
INTO corelogic_usda.current_tax_200627_latest_all_add_vars
FROM corelogic_usda.current_tax_200627_latest_all;

ALTER TABLE corelogic_usda.current_tax_200627_latest_all_add_vars ADD PRIMARY KEY (geoid_cnty, p_id_iris_frmtd);
```
