---
title: "Create Table of All Properties within 20 Miles of Program Boundaries"
output: 
  html_document:
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  eval=FALSE)
```

## Create table of property data converted to CRS 26918 (to work in meters), index geo for spatial joins

```{sql}
select geoid_cnty, p_id_iris_frmtd, st_transform(geometry, 26918) geometry 
into corelogic_usda.current_tax_200627_latest_locs_geom_26918
from corelogic_usda.current_tax_200627_latest_all_add_vars_add_progs_geom_blk ctlaavapgb;

create index current_tax_200627_latest_locs_geom_26918_idx on corelogic_usda.current_tax_200627_latest_locs_geom_26918 using GIST (geometry);
```

## CC

### Convert CC Table to CRS 26918 (to work in meters), index geo

```{sql}
select *, st_transform(geometry, 26918) geom 
into usda_bb.cc_program_areas_26918
from usda_bb.cc_program_areas bpa;

create index cc_program_areas_26918_geom_idx on usda_bb.cc_program_areas_26918 using gist(geom);
```

### Add a line string representing the exterior ring of the POLYGON geometry

```{sql}
SELECT rusid, geom, ST_Collect(ST_ExteriorRing(ring_geom)) AS ring_geom
into usda_bb.cc_program_areas_ring_26918
FROM (SELECT "RUSID" rusid, geom, (ST_Dump(geom)).geom As ring_geom
			FROM usda_bb.cc_program_areas_26918) As foo
GROUP BY rusid, geom;

create index cc_with_ring_geom_idx on usda_bb.cc_program_areas_ring_26918 using GIST (ring_geom);
create index cc_with_ring_geom_26918_idx on usda_bb.cc_program_areas_ring_26918 using GIST (geom);

```

### Create table of every property within 20 miles of a CC boundary, index id, distance, and links to property table

```{sql}
select a.rusid, b.geoid_cnty, b.p_id_iris_frmtd, st_within(b.geometry, a.geom) in_rusid, min(st_distance(b.geometry, a.ring_geom)) dist_ring_meters
into usda_bb.cc_program_area_properties_20mi
from usda_bb.cc_program_areas_ring_26918 a 
inner join corelogic_usda.current_tax_200627_latest_locs_geom_26918 b on st_dwithin(b.geometry, a.geom , 32186.88)
where a.rusid is not null
group by a.rusid, b.geoid_cnty, b.p_id_iris_frmtd, st_within(b.geometry, a.geom), st_distance(b.geometry, a.geom);

create index cc_20mi_geoid_cnty_idx on usda_bb.cc_program_area_properties_20mi (geoid_cnty);
create index cc_20mi_p_id_iris_frmtd_idx on usda_bb.cc_program_area_properties_20mi (p_id_iris_frmtd);
```

## BIP

### Convert BIP Table to CRS 26918 (to work in meters), index geo

```{sql}
select *, st_transform(geometry, 26918) geom 
into usda_bb.bip_program_areas_26918
from usda_bb.bip_program_areas bpa;

create index bip_program_areas_26918_geom_idx on usda_bb.bip_program_areas_26918 using gist(geom);
```

### Add a line string representing the exterior ring of the POLYGON geometry

```{sql}
SELECT rusid, geom, ST_Collect(ST_ExteriorRing(ring_geom)) AS ring_geom
into usda_bb.bip_program_areas_ring_26918
FROM (SELECT "RUS_ID" rusid, geom, (ST_Dump(geom)).geom As ring_geom
			FROM usda_bb.bip_program_areas_26918) As foo
GROUP BY rusid, geom;

create index bip_with_ring_geom_idx on usda_bb.bip_program_areas_ring_26918 using GIST (ring_geom);
create index bip_with_ring_geom_26918_idx on usda_bb.bip_program_areas_ring_26918 using GIST (geom);
```

### Create table of every property within 20 miles of a BIP boundary, index id, distance, and links to property table

```{sql}
select a.rusid, b.geoid_cnty, b.p_id_iris_frmtd, st_within(b.geometry, a.geom) in_rusid, min(st_distance(b.geometry, a.ring_geom)) dist_ring_meters
into usda_bb.bip_program_area_properties_20mi
from usda_bb.bip_program_areas_ring_26918 a 
inner join corelogic_usda.current_tax_200627_latest_locs_geom_26918 b on st_dwithin(b.geometry, a.geom , 32186.88)
where a.rusid is not null
group by a.rusid, b.geoid_cnty, b.p_id_iris_frmtd, st_within(b.geometry, a.geom), st_distance(b.geometry, a.geom);

create index bip_20mi_geoid_cnty_idx on usda_bb.bip_program_area_properties_20mi (geoid_cnty);
create index bip_20mi_p_id_iris_frmtd_idx on usda_bb.bip_program_area_properties_20mi (p_id_iris_frmtd);
```

## RC

### Convert RC Table to CRS 26918 (to work in meters), index geo

```{sql}
select *, st_transform(geometry, 26918) geom 
into usda_bb.rc_program_areas_26918
from usda_bb.rc_program_areas;

create index rc_program_areas_26918_geom_idx on usda_bb.rc_program_areas_26918 using gist(geom);
```

### Add a line string representing the exterior ring of the POLYGON geometry

```{sql}
SELECT rusid, geom, ST_Collect(ST_ExteriorRing(ring_geom)) AS ring_geom
into usda_bb.rc_program_areas_ring_26918
FROM (SELECT "RUS_ID" rusid, geom, (ST_Dump(geom)).geom As ring_geom
			FROM usda_bb.rc_program_areas_26918) As foo
GROUP BY rusid, geom;

create index rc_with_ring_geom_idx on usda_bb.rc_program_areas_ring_26918 using GIST (ring_geom);
create index rc_with_ring_geom_26918_idx on usda_bb.rc_program_areas_ring_26918 using GIST (geom);

```

### Create table of every property within 20 miles of a RC boundary, index id, distance, and links to property table

```{sql}
select a.rusid, b.geoid_cnty, b.p_id_iris_frmtd, st_within(b.geometry, a.geom) in_rusid, min(st_distance(b.geometry, a.ring_geom)) dist_ring_meters
into usda_bb.rc_program_area_properties_20mi
from usda_bb.rc_program_areas_ring_26918 a 
inner join corelogic_usda.current_tax_200627_latest_locs_geom_26918 b on st_dwithin(b.geometry, a.geom , 32186.88)
where a.rusid is not null
group by a.rusid, b.geoid_cnty, b.p_id_iris_frmtd, st_within(b.geometry, a.geom), st_distance(b.geometry, a.geom);

create index rc_20mi_geoid_cnty_idx on usda_bb.rc_program_area_properties_20mi (geoid_cnty);
create index rc_20mi_p_id_iris_frmtd_idx on usda_bb.rc_program_area_properties_20mi (p_id_iris_frmtd);
```

## TCF

### Convert TCF Table to CRS 26918 (to work in meters), index geo

```{sql}
select *, st_transform(geometry, 26918) geom 
into usda_bb.tcf_program_areas_26918
from usda_bb.tcf_program_areas;

create index tcf_program_areas_26918_geom_idx on usda_bb.tcf_program_areas_26918 using gist(geom);
```

### Add a line string representing the exterior ring of the POLYGON geometry

```{sql}
SELECT rusid, geom, ST_Collect(ST_ExteriorRing(ring_geom)) AS ring_geom
into usda_bb.tcf_program_areas_ring_26918
FROM (SELECT "RUS_ID" rusid, geom, (ST_Dump(geom)).geom As ring_geom
			FROM usda_bb.tcf_program_areas_26918) As foo
GROUP BY rusid, geom;

create index tcf_with_ring_geom_idx on usda_bb.tcf_program_areas_ring_26918 using GIST (ring_geom);
create index tcf_with_ring_geom_26918_idx on usda_bb.tcf_program_areas_ring_26918 using GIST (geom);
```

### Create table of every property within 20 miles of a TCF boundary, index id, distance, and links to property table

```{sql}
select a.rusid, b.geoid_cnty, b.p_id_iris_frmtd, st_within(b.geometry, a.geom) in_rusid, min(st_distance(b.geometry, a.ring_geom)) dist_ring_meters
into usda_bb.tcf_program_area_properties_20mi
from usda_bb.tcf_program_areas_ring_26918 a 
inner join corelogic_usda.current_tax_200627_latest_locs_geom_26918 b on st_dwithin(b.geometry, a.geom , 32186.88)
where a.rusid is not null
group by a.rusid, b.geoid_cnty, b.p_id_iris_frmtd, st_within(b.geometry, a.geom), st_distance(b.geometry, a.geom);

create index tcf_20mi_geoid_cnty_idx on usda_bb.tcf_program_area_properties_20mi (geoid_cnty);
create index tcf_20mi_p_id_iris_frmtd_idx on usda_bb.tcf_program_area_properties_20mi (p_id_iris_frmtd);
```

## TCI

### Convert TCI Table to CRS 26918 (to work in meters), index geo

```{sql}
select *, st_transform(geometry, 26918) geom 
into usda_bb.tci_program_areas_26918
from usda_bb.tci_program_areas;

create index tci_program_areas_26918_geom_idx on usda_bb.tci_program_areas_26918 using gist(geom);
```

### Add a line string representing the exterior ring of the POLYGON geometry

```{sql}
SELECT rusid, geom, ST_Collect(ST_ExteriorRing(ring_geom)) AS ring_geom
into usda_bb.tci_program_areas_ring_26918
FROM (SELECT "RUSID" rusid, geom, (ST_Dump(geom)).geom As ring_geom
			FROM usda_bb.tci_program_areas_26918) As foo
GROUP BY rusid, geom;

create index tci_with_ring_geom_idx on usda_bb.tci_program_areas_ring_26918 using GIST (ring_geom);
create index tci_with_ring_geom_26918_idx on usda_bb.tci_program_areas_ring_26918 using GIST (geom);
```

### Create table of every property within 20 miles of a TCI boundary, index id, distance, and links to property table

```{sql}
select a.rusid, b.geoid_cnty, b.p_id_iris_frmtd, st_within(b.geometry, a.geom) in_rusid, min(st_distance(b.geometry, a.ring_geom)) dist_ring_meters
into usda_bb.tci_program_area_properties_20mi
from usda_bb.tci_program_areas_ring_26918 a 
inner join corelogic_usda.current_tax_200627_latest_locs_geom_26918 b on st_dwithin(b.geometry, a.geom , 32186.88)
where a.rusid is not null
group by a.rusid, b.geoid_cnty, b.p_id_iris_frmtd, st_within(b.geometry, a.geom), st_distance(b.geometry, a.geom);

create index tci_20mi_geoid_cnty_idx on usda_bb.tci_program_area_properties_20mi (geoid_cnty);
create index tci_20mi_p_id_iris_frmtd_idx on usda_bb.tci_program_area_properties_20mi (p_id_iris_frmtd);
```

## Create single table of all properties within 20 miles of USDA broadband program boundaries, add indexes for link and search

```{sql}
select *
into usda_bb.rus_program_property_distances_to_20m_b
from 
(
select * from
(select 'BIP' rus_prog, rusid rus_id, geoid_cnty, p_id_iris_frmtd, in_rusid, round(dist_ring_meters::numeric/1609.344, 2) distance_mi
from usda_bb.bip_program_area_properties_20mi) a 
union
select * from
(select 'CC' rus_prog, rusid rus_id, geoid_cnty, p_id_iris_frmtd, in_rusid, round(dist_ring_meters::numeric/1609.344, 2) distance_mi
from usda_bb.cc_program_area_properties_20mi) b 
union
select * from
(select 'RC' rus_prog, rusid rus_id, geoid_cnty, p_id_iris_frmtd, in_rusid, round(dist_ring_meters::numeric/1609.344, 2) distance_mi
from usda_bb.rc_program_area_properties_20mi) c
union
select * from
(select 'TCF' rus_prog, rusid rus_id, geoid_cnty, p_id_iris_frmtd, in_rusid, round(dist_ring_meters::numeric/1609.344, 2) distance_mi
from usda_bb.tcf_program_area_properties_20mi) d
union
select * from
(select 'TCI' rus_prog, rusid rus_id, geoid_cnty, p_id_iris_frmtd, in_rusid, round(dist_ring_meters::numeric/1609.344, 2) distance_mi
from usda_bb.tci_program_area_properties_20mi) e
) t;

create index rppd_20_prop_idx on usda_bb.rus_program_property_distances_to_20mi (geoid_cnty, p_id_iris_frmtd);
create index rppd_20_rusid_idx on usda_bb.rus_program_property_distances_to_20mi (rus_id);
create index rppd_20_rusprog_idx on usda_bb.rus_program_property_distances_to_20mi (rus_prog);
```
