---
title: "Import Data File"
output: 
  html_document:
    toc: yes
    toc_float: yes
    toc_depth: 4
editor_options: 
  markdown: 
    wrap: 72
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  eval=FALSE
)
```

------------------------------------------------------------------------

## FCC 

### Form 477

#### Download 2014 Data

```{r}
# url <- "http://transition.fcc.gov/form477/BroadbandData/Fixed/Dec14/Version%203/US-Fixed-without-Satellite-Dec2014.zip"
# temp <- tempfile()
# download.file(url,temp)
# unlink(temp)

# grab temp pathname and go intoto terminal 
# ran this to see name of file in zip 
# unzip -l /tmp/RtmpwK6I3G/file33274b60567b
# ran this to unzip from terminal:
# unzip /tmp/RtmpwK6I3G/file33274b60567b -d /project/biocomplexity/sdad/projects_data/project_data/usda/rural_broadband/fcc_availability/

fcc_2014 <- read.csv("/project/biocomplexity/sdad/projects_data/project_data/usda/rural_broadband/fcc_availability/fbd_us_without_satellite_dec2014_v3.csv")
```

#### Download 2018 data

```{r}
# url <- "<https://www.fcc.gov/form477/BroadbandData/Fixed/Dec18/Version%202/US-Fixed-without-Satellite-Dec2018.zip>"
# temp <- tempfile()
# download.file(url,temp)
# unlink(temp)
# grab temp pathname and go intoto terminal
# ran this to see name of file in zip
# unzip -l /tmp/RtmpSdiLsM/file360be78486be5
# ran this to unzip from terminal:
# unzip /tmp/RtmpSdiLsM/file360be78486be5 -d /project/biocomplexity/sdad/projects_data/project_data/usda/rural_broadband/fcc_availability/

```


## USDA 

### Non-Rural Areas
N/A - simply downloaded

### Protected Borrowers
N/A - simply downloaded

### CAF II 
N/A - simply downloaded

### RUS Program Service Areas: Community Connect, ReConnect 
N/A - simply downloaded

## Census 

### Census Blocks
Also had a bunch of code to check complete download of data

```{r}
# setwd("~/censusblocks/blocks_TIGER2018_zips_shapes/")
# download.file(links$LINKS[], destfile = links$NAME[])
# xmlfiles <- unzip(temp, exdir = tdir)
```

