---
title: "USDA-ERS Broadband Rural Impact"
output: 
  html_document:
    toc: yes
    toc_float: yes
    toc_depth: 4
---

```{r echo=FALSE, results='asis', message=FALSE}
library(htmltools)
library(data.table)
library(DT)
source("../R/functions.R")

ds_info_files <- list.files(pattern = "*_00*.Rmd")

for (ds in ds_info_files) {
  rmd_yml <- extract_rmd_yml(ds)
  ds <- rmd_yml$dataset
  dt <- as.data.table(t(as.data.table(ds)), keep.rownames = T)
  colnames(dt) <- c("Item", "Value")
  print(h3(paste("Dataset:", dt[Item == "dataset_short_title", Value])))
  print(knitr::kable(dt[Item != "dataset_short_title",], col.names = c("", "")))
}
```

```{r future_dynamic_menus, include=FALSE}
# fp <- list.files(pattern = "*_01*.Rmd")
# rmd_yml <- extract_rmd_yml(fp)
# 
# library(magrittr)
# navbar <- readr::read_lines("_navbar.html")
# nb <- xml2::read_html("_navbar.html")
# rvest::html_node(nb, "#topdiv") %>% 
#   rvest::html_attr("role")
# 
# 
# xml2::write_html(nb, "test.html")

# navbar <- stringr::str_replace(navbar, '<a href="dp_ds01_01.html">Parallel Import</a>', paste0('<a href="dp_ds01_01.html">', rmd_yml$menu_title, '</a>'))
# readr::write_lines(navbar, "_navbar.html")
```
